CREATE TABLE trainers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    specialization VARCHAR(150),
    description VARCHAR(500)
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone_number VARCHAR(30),
    join_date DATE NOT NULL
);

CREATE TABLE class_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    start_time TIMESTAMP NOT NULL,
    max_participants INT NOT NULL,
    trainer_id BIGINT NOT NULL,
    CONSTRAINT fk_class_session_trainer
        FOREIGN KEY (trainer_id) REFERENCES trainers (id)
);

CREATE TABLE memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    member_id BIGINT NOT NULL,
    CONSTRAINT fk_membership_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    class_session_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reservation_member
        FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_reservation_class_session
        FOREIGN KEY (class_session_id) REFERENCES class_sessions (id)
);




